
  DECLARE @ID AS INT
  DECLARE @LASTID AS INT = 0
  DECLARE @CITY AS NVARCHAR(50)
  DECLARE @TOWN AS  NVARCHAR(50)
  DECLARE @TELNR AS NVARCHAR(100)
  DECLARE @NAME AS VARCHAR(50)
  DECLARE @GENDER AS NVARCHAR(10)
  DECLARE @SURNAME AS VARCHAR(150)
  DECLARE @NAME_SURNAME AS NVARCHAR(100)
  DECLARE @BIRTHDATE AS DATE	
  SET @BIRTHDATE = DATEFROMPARTS(ROUND(RAND()*200+1900,0),ROUND(RAND()*11+1,0),ROUND(RAND()*30+1,0))
  --SELECT @BIRTHDATE

  SET @ID=ROUND(RAND()*611,0)
  --SELECT ROUND(RAND()*611,0)
  
  SELECT @NAME=NAME_ , @GENDER=GENDER FROM NAMES WHERE ID=@ID
 -- SELECT @NAME, @GENDER,@ID

  SET @ID=ROUND(RAND()*1000,0)
  --SELECT ROUND(RAND()*200+1900,0)
  --SELECT ROUND(RAND()*200,0)
  SELECT @SURNAME=SURNAME FROM SURNAMES WHERE ID=@ID
  --SELECT @SURNAME, @ID

  SET @NAME_SURNAME=@NAME + ' ' +@SURNAME

  SET @ID=ROUND(RAND()*995,0)
   SELECT @CITY=CITY, @TOWN=TOWN FROM CITY_DISTRICT WHERE ID=@ID
  --SELECT @CITY, @TOWN, @ID

  SET @ID=ROUND(RAND()*1000,0)
  SELECT @TELNR=TELNR FROM TELEPHONES WHERE @ID=ID

   SELECT @NAME_SURNAME, @GENDER, @BIRTHDATE, @CITY,@TOWN, @TELNR
   SELECT TOP 1 @LASTID=ID FROM RECORDS ORDER BY ID DESC
   SET @LASTID=@LASTID+1
   SELECT @LASTID

 INSERT INTO RECORDS (ID,NAMESURNAME, GENDER, BIRTHDATE, CITY, TOWN, TELNR) VALUES (@LASTID,@NAME_SURNAME, @GENDER, @BIRTHDATE, @CITY, @TOWN, @TELNR)
 SELECT * FROM RECORDS

