/* IOT ORNEGI ORNEK UYGULAMA: -10 SN DE BIR SICAKLIK SENSORUNDEN VERI OKUYAN BIR IOT PROJESI YAPIYORUZ
-ICERISINDE TARIH-SAAT DEGERI ILE SICAKLIK DEGERINI BULUNDURAN BIR TABLO OLUSTURUNUZ. 
-BU TABLOYA RASTGELE OLUSTURDUGUMUZ SICAKLIK VE TARIH SAAT DEGERINI KAYIT OLARAK ATINIZ. 
-10 SANIYEDE 1 BU SORGUYU CALISTIRACAK BIR MEKANIZMA KURUNUZ. 
*/

---SET @SICAKLIK= Round(RAND()+1,2)+10 - round(RAND()+1,2)+10 , burada 10 deðerini son sýcaklýðýn deðeri neyse onun deðiþken olarak gelmesi gerekmekte.

DECLARE @LASTSENSORVALUE AS FLOAT

SELECT TOP (1) @LASTSENSORVALUE=SENSOR_VALUE FROM SENSOR ORDER BY datetime_ DESC
--SELECT @LASTSENSORVALUE

DECLARE @SENSOR_ID AS INT=1
DECLARE @DATE_ AS DATETIME


DECLARE @SICAKLIK AS FLOAT
SET @SICAKLIK= @LASTSENSORVALUE +(RAND()+1) -(RAND()+1)
SET @SICAKLIK=ROUND(@SICAKLIK,2)


INSERT INTO SENSOR (SENSOR_ID,datetime_,SENSOR_VALUE ) VALUES (@SENSOR_ID,GETDATE(),@SICAKLIK)


select * from SENSOR
--SELECT Round(RAND()+1,2)

--NOT:
--UYGULAMADA 10 SN DE BÝR SICAKLIK SENSÖRÜNDEN VERÝ OKUMASI GEREKLÝLÝÐÝNÝ BELÝRTÝLMÝÞ. BU DA 10 SN DE BÝR datetime_ alanýnýn güncellenmesi demektir.
--SQL'de otomatik ve periyodik olarak çalýþacak iþlemleri takip etmek için "SQL SERVER AGENT" aracý kullanýlýr. Tarih alaný þimdiki tarih+10 sn þeklinde job ile getirilecektir.
