/* T-SQL PROGRAMLAMA
T-SQL'DE DEÐÝÞKEN TANIMI:
DECLARE komutu deðiþken tanýmlanýrken kullanýlýr. Deðiþken tanýmlarken ise deðiþkenin belli olmasý adýna deðiþken ismi önüne @ iþareti getirilir.
En son ise deðiþkene veri tipi atanýr. Deðiþkene deðer atayabilmek için ise SET komutu kullanýlýr ve SET @variable_name = value þeklinde yapý oluþturulur.
Sorgularý select ile görmek için toplu run edilmesi gerekilmekte.
*/

DECLARE @NUMBER AS INT
SET @NUMBER=52
SELECT @NUMBER
DECLARE @NUMBER2 AS INTEGER
SET @NUMBER2 =10
DECLARE @TOTAL_NUMBER AS INT
SET @TOTAL_NUMBER = @NUMBER+@NUMBER2
SELECT @NUMBER , @NUMBER2 , @TOTAL_NUMBER

---

DECLARE @DT AS DATETIME
SET @DT= '2023-03-22 16:04:00'
SELECT @DT
declare @YEAR AS INT
DECLARE @MONTH AS INT
DECLARE @DAY AS INT
DECLARE @HOUR AS INT
DECLARE @MINUTE AS INT
DECLARE @SECOND AS INT

SET @YEAR = YEAR(@DT)
SET @MONTH = MONTH(@DT)
SET @DAY = DAY(@DT)
SET @HOUR = DATEPART(HOUR,@DT)
SET @MINUTE = DATEPART(MINUTE,@DT)
SET @SECOND = DATEPART(SECOND,@DT)

SELECT @DT, @YEAR, @MONTH, @DAY, @HOUR, @MINUTE, @SECOND

-------
DECLARE @DT AS DATETIME

SELECT @DT
declare @YEAR AS INT
DECLARE @MONTH AS INT
DECLARE @DAY AS INT
DECLARE @HOUR AS INT
DECLARE @MINUTE AS INT
DECLARE @SECOND AS INT

SET @YEAR = 2023
SET @MONTH = 3
SET @DAY = 22
SET @HOUR = 16
SET @MINUTE = 04
SET @SECOND = 00

SET @DT = DATETIMEFROMPARTS( @YEAR, @MONTH, @DAY, @HOUR, @MINUTE, @SECOND,0)
SELECT @DT, @YEAR, @MONTH, @DAY, @HOUR, @MINUTE, @SECOND

-----

DECLARE @NAME AS VARCHAR(100)
DECLARE @SURNAME AS VARCHAR(200)
DECLARE @NAMESURNAME AS VARCHAR(300)
SET @NAME = 'BAHAR'
SET @SURNAME = 'ERTURUL'
SET @NAMESURNAME=@NAME+ ' ' +@SURNAME
SELECT @NAMESURNAME,@NAME,@SURNAME

--DEÐÝÞKENE DEFAULT DEÐER TANIMLAMA : SET KOMUTU KULLANMADAN SABÝT DEÐER TANIMLANMAKTA.
DECLARE @DEFAULT AS VARCHAR(100) = 'DEFAULT DEÐER TANIMLAMA'
SELECT @DEFAULT
